In [ ]:
!pip install inltk

     |████████████████████████████████| 1.3MB 30.9MB/s 
     |████████████████████████████████| 81kB 7.7MB/s 
     |████████████████████████████████| 235kB 41.3MB/s 
     |████████████████████████████████| 1.2MB 41.6MB/s 
     |████████████████████████████████| 143kB 51.0MB/s 
     |████████████████████████████████| 296kB 54.2MB/s 
  Created wheel for typing: filename=typing-3.7.4.3-cp37-none-any.whl size=26308 sha256=12546f77cab8c785f5f113d4e33b1aa0af83f483186efb17a71d8b024818fe5b
  Stored in directory: /root/.cache/pip/wheels/2d/04/41/8e1836e79581989c22eebac3f4e70aaac9af07b0908da173be
Successfully built typing
  Found existing installation: fastai 1.0.61
    Uninstalling fastai-1.0.61:
      Successfully uninstalled fastai-1.0.61


In [ ]:
!pip install -U torchtext==0.8.0


Requirement already up-to-date: torchtext==0.8.0 in /usr/local/lib/python3.7/dist-packages (0.8.0)


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from inltk.inltk import setup

setup('te')

In [ ]:
setup('ml')

In [ ]:
import numpy as np
import pandas as pd
import collections
from inltk.inltk import tokenize

In [ ]:
telugu_path = '/content/drive/MyDrive/Sem-2/NLP/DataSets/ml-te/train.te'
malayalam_path = '/content/drive/MyDrive/Sem-2/NLP/DataSets/ml-te/train.ml'

In [ ]:
def readLines(path):
  file = open(str(path),'r')
  line_list = []
  Lines = file.readlines()
  #count = 0
  # Strips the newline character
  for line in Lines:
      #count += 1
      #print("Line{}: {}".format(count, line.strip()))
      line_list.append(line.strip())
  return line_list

In [ ]:
tel_list = readLines(telugu_path)
mal_list = readLines(malayalam_path)
print(len(tel_list))
print(len(mal_list))

10480
10480


In [ ]:
telugu_words_counter = collections.Counter([word for sentence in tel_list for word in sentence.split()])
print('{} Telugu words.'.format(len([word for sentence in tel_list for word in sentence.split()])))
print('No. of unique (Telugu) words = ',len(telugu_words_counter))
mallu_words_counter = collections.Counter([word for sentence in mal_list for word in sentence.split()])
print('{} Malayalam  words.'.format(len([word for sentence in mal_list for word in sentence.split()])))
print('No. of unique (Malayalam) words = ',len(mallu_words_counter))



215153 Telugu words.
No. of unique (Telugu) words =  49216
167853 Malayalam  words.
No. of unique (Malayalam) words =  52708


In [ ]:
tokenizer = Tokenizer(num_words=100, lower= 1, oov_token="<OOV>")
tokenizer.fit_on_texts(tel_list[0])
word_index = tokenizer.word_index
print(word_index)


In [ ]:
df = pd.DataFrame(
    {'Telugu': tel_list,
     'Mallu': mal_list,
    })
df

Telugu                                              Mallu
0      2017-18 సంవత్సరంలో ఈ క్యాంపెయిన్ ను నిర్వహించడ...  2017-18ലെ ബജറ്റില്‍ ന്യൂനപക്ഷമന്ത്രാലയത്തിന് 4...
1      తమ ప్రభుత్వం సంతృప్తిపరచడానికి బదులు, సాధికారత...  ഇന്ത്യയുടെ ഹജ്ജ്ക്വാട്ടയില്‍ സൗദി ഗവണ്‍മെന്റ് ...
2      ఈ రెండు మంత్రిత్వ‌ శాఖ‌ల పాల‌న నియంత్ర‌ణ కింద‌...  ഇന്ത്യ ഇന്ന് ലോകത്തിന്റെ മരുന്നുനിര്‍മാണശാലയാണ...
3      మంత్రిమండలి ఏన్షంట్ మాన్యుమెంట్స్ అండ్ ఆర్కియా...  മന്ത്രിസഭ പുരാതന സ്മാരകങ്ങളും പുരാവസ്തു അവശിഷ്...
4      పూర్వరంగం: రెండు దేశాల కస్టమ్స్ అధికారుల మధ్య ...  പശ്ചാത്തലം ഇരു രാജ്യങ്ങളിലെയും കസ്റ്റംസ് അധികൃ...
...                                                  ...                                                ...
10475  కేంద్ర ఆరోగ్య, కుటుంబ సంక్షేమ శాఖ సహాయ మంత్రి ...  ആരോഗ്യ, കുടുംബക്ഷേമ സഹമന്ത്രി ശ്രീ അശ്വിനി കുമ...
10476  లేని పని ప్రదేశాల కోసం సి.ఐ.ఐ. ప్రచారం అనే అంశ...  ആരോഗ്യസംരക്ഷണത്തെക്കുറിച്ചുള്ള ഒരു വെർച്വൽ എക്...
10477  యొక్క ఆర్థిక భారం చాలా ఎక్కువగా ఉంది. ఇది అపరి...  ജീവനും പണവും തൊഴിൽ ദിനങ്ങളും കണക്കിലെടുക്കുമ്പ...
10478  ఈ సమస్యపై ప్రభుత్వం స్పందన గురించి ఆయన ప్రత్యే...  ക്ഷയരോഗചികിൽസക്കുള്ള വിഭവ വിഹിതം കഴിഞ്ഞ അഞ്ചുവ...
10479  "ఇ-సంజీవని టెలి-కన్సల్టేషన్ వేదికపై ఇప్పటికే న...  ഇ- സഞ്ജീവനി ടെലി കൺസൾട്ടേഷൻ പ്ലാറ്റ്‌ഫോമിലൂടെ ...

[10480 rows x 2 columns]

In [ ]:
tokenize(tel_list[0],'te')

['▁2017',
 '-18',
 '▁సంవత్సరంలో',
 '▁ఈ',
 '▁క్యా',
 'ం',
 'పె',
 'యిన్',
 '▁ను',
 '▁నిర్వహించడం',
 '▁జరుగుతుందని',
 ',',
 '▁ఇందుకోసం',
 '▁100',
 '▁జిల్లా',
 'లను',
 '▁గుర్తించిన',
 'ట్లు',
 '▁చెప్పారు',
 '.']

**Preprocessing**

Converting the text into sequences of integers using the following preprocess methods:

1) Tokenize the words into ids

2) Add padding to make all the sequences the same length.

In [ ]:
from tqdm import tqdm

tokenized_data = {
    'te' : [],
    'ml' : []
}

def tokenize(list1,lang):
  global tokenized_data
  tokenized_list = []
  for i in tqdm(range(len(list1))):
    tokenized_list = tokenize(list1[i],str(lang))
    tokenized_data[str(lang)].append(tokenized_list)
  #return tokenized_data


In [ ]:
import sys
sys.setrecursionlimit(1500)

In [ ]:
#Tokenizing Telugu dataset
from inltk.inltk import tokenize
from tqdm import tqdm

tokenized_data = {
    'te' : [],
    'ml' : []
}
for i in (range(len(tel_list))):
    #print(" ",end='\r')
    tokenized_list = tokenize(tel_list[i],'te')
    tokenized_data['te'].append(tokenized_list)
    #print(i,end = '\r')

#tokenize(tel_list,'te')
#tokenized_data

In [ ]:
#Tokenizing Malayalam Data Set
from inltk.inltk import tokenize

for i in (range(len(mal_list))):
    #print(" ",end='\r')
    tokenized_list = tokenize(mal_list[i],'ml')
    tokenized_data['ml'].append(tokenized_list)
    #print(i,end = '\r')

#tokenize(tel_list,'te')
#tokenized_data

In [ ]:
df_tokenized_data = pd.DataFrame.from_dict(tokenized_data)
df_tokenized_data

te                                                 ml
0      [▁2017, -18, ▁సంవత్సరంలో, ▁ఈ, ▁క్యా, ం, పె, యి...  [▁2017, -, 18, ലെ, ▁ബ, ജ, റ്റി, ല്, ▁ന്യൂനപക്ഷ...
1      [▁తమ, ▁ప్రభుత్వం, ▁సంతృప్తి, పరచడానికి, ▁బదులు...  [▁ഇന്ത്യയുടെ, ▁ഹജ്ജ്, ക്, വാ, ട്ട, യില, ്, ▁സൗ...
2      [▁ఈ, ▁రెండు, ▁మంత్రిత్వ, ▁శాఖ, ▁ల, ▁పాల, ▁న, ▁...  [▁ഇന്ത്യ, ▁ഇന്ന്, ▁ലോക, ത്തിന്റെ, ▁മര, ുന്നു, ...
3      [▁మంత్రి, మండలి, ▁ఏ, న్, ష, ంట్, ▁మాన్, యు, మె...  [▁മന്ത്രിസഭ, ▁പുരാതന, ▁സ്മാരക, ങ്ങളും, ▁പുരാവസ...
4      [▁పూర్వ, రంగం, :, ▁రెండు, ▁దేశాల, ▁క, స్ట, మ్స...  [▁പശ്ചാത്തല, ം, ▁ഇരു, ▁രാജ്യങ്ങളിലെ, യും, ▁ക, ...
...                                                  ...                                                ...
10475  [▁కేంద్ర, ▁ఆరోగ్య, ,, ▁కుటుంబ, ▁సంక్షేమ, ▁శాఖ,...  [▁ആരോഗ്യ, ,, ▁കുടുംബ, ക്ഷ, േ, മ, ▁സഹ, മന്ത്രി,...
10476  [▁లేని, ▁పని, ▁ప్రదేశాల, ▁కోసం, ▁సి, ., ఐ, ., ...  [▁ആരോഗ്യ, സംരക്ഷണ, ത്ത, െക്കുറിച്ചുള്ള, ▁ഒരു, ...
10477  [▁యొక్క, ▁ఆర్థిక, ▁భారం, ▁చాలా, ▁ఎక్కువగా, ▁ఉం...  [▁ജീവന, ും, ▁പണ, വും, ▁തൊഴിൽ, ▁ദിന, ങ്ങളും, ▁ക...
10478  [▁ఈ, ▁సమస్య, పై, ▁ప్రభుత్వం, ▁స్పందన, ▁గురించి...  [▁, ക്ഷയ, രോഗ, ചി, ക, ിൽ, സ, ക്കുള്ള, ▁വിഭവ, ▁...
10479  [▁", ఇ, -, సం, జీవ, ని, ▁టెలి, -, కన్, సల్, టే...  [▁ഇ, -, ▁സ, ഞ്ജ, ീ, വ, നി, ▁ടെലി, ▁കൺ, സ, ൾ, ട...

[10480 rows x 2 columns]

In [ ]:
for i in range(len(df_tokenized_data['te'][0])):
  if '▁' in df_tokenized_data['te'][0][i]:
    df_tokenized_data['te'][0][i] = df_tokenized_data['te'][0][i].replace('▁','')

In [ ]:
df_tokenized_data['te'][0]

['2017',
 '18',
 'సంవత్సరంలో',
 'ఈ',
 'క్యా',
 'ం',
 'పె',
 'యిన్',
 'ను',
 'నిర్వహించడం',
 'జరుగుతుందని',
 ',',
 'ఇందుకోసం',
 '100',
 'జిల్లా',
 'లను',
 'గుర్తించిన',
 'ట్లు',
 'చెప్పారు',
 '.']

In [ ]:
for j in range(len(df_tokenized_data['te'])):
  for i in range(len(df_tokenized_data['te'][j])):
    df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('▁','')
    df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('-','')
    df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('@','')
    #df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('\','')
    #df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('/','')
    df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('>','')
    df_tokenized_data['te'][j][i] = df_tokenized_data['te'][j][i].replace('<','')  

In [ ]:
df_tokenized_data

te                                                 ml
0      [2017, 18, సంవత్సరంలో, ఈ, క్యా, ం, పె, యిన్, న...  [▁2017, -, 18, ലെ, ▁ബ, ജ, റ്റി, ല്, ▁ന്യൂനപക്ഷ...
1      [తమ, ప్రభుత్వం, సంతృప్తి, పరచడానికి, బదులు, ,,...  [▁ഇന്ത്യയുടെ, ▁ഹജ്ജ്, ക്, വാ, ട്ട, യില, ്, ▁സൗ...
2      [ఈ, రెండు, మంత్రిత్వ, శాఖ, ల, పాల, న, నియంత్ర,...  [▁ഇന്ത്യ, ▁ഇന്ന്, ▁ലോക, ത്തിന്റെ, ▁മര, ുന്നു, ...
3      [మంత్రి, మండలి, ఏ, న్, ష, ంట్, మాన్, యు, మెంట్...  [▁മന്ത്രിസഭ, ▁പുരാതന, ▁സ്മാരക, ങ്ങളും, ▁പുരാവസ...
4      [పూర్వ, రంగం, :, రెండు, దేశాల, క, స్ట, మ్స్, అ...  [▁പശ്ചാത്തല, ം, ▁ഇരു, ▁രാജ്യങ്ങളിലെ, യും, ▁ക, ...
...                                                  ...                                                ...
10475  [కేంద్ర, ఆరోగ్య, ,, కుటుంబ, సంక్షేమ, శాఖ, సహాయ...  [▁ആരോഗ്യ, ,, ▁കുടുംബ, ക്ഷ, േ, മ, ▁സഹ, മന്ത്രി,...
10476  [లేని, పని, ప్రదేశాల, కోసం, సి, ., ఐ, ., ఐ, .,...  [▁ആരോഗ്യ, സംരക്ഷണ, ത്ത, െക്കുറിച്ചുള്ള, ▁ഒരു, ...
10477  [యొక్క, ఆర్థిక, భారం, చాలా, ఎక్కువగా, ఉంది, .,...  [▁ജീവന, ും, ▁പണ, വും, ▁തൊഴിൽ, ▁ദിന, ങ്ങളും, ▁ക...
10478  [ఈ, సమస్య, పై, ప్రభుత్వం, స్పందన, గురించి, ఆయన...  [▁, ക്ഷയ, രോഗ, ചി, ക, ിൽ, സ, ക്കുള്ള, ▁വിഭവ, ▁...
10479  [", ఇ, , సం, జీవ, ని, టెలి, , కన్, సల్, టేషన్,...  [▁ഇ, -, ▁സ, ഞ്ജ, ീ, വ, നി, ▁ടെലി, ▁കൺ, സ, ൾ, ട...

[10480 rows x 2 columns]

In [ ]:
for j in range(len(df_tokenized_data['ml'])):
  for i in range(len(df_tokenized_data['ml'][j])):
    df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('▁','')
    df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('-','')
    df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('@','')
    #df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('\','')
    #df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('/','')
    df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('>','')
    df_tokenized_data['ml'][j][i] = df_tokenized_data['ml'][j][i].replace('<','')  

In [ ]:
df_tokenized_data

te                                                 ml
0      [2017, 18, సంవత్సరంలో, ఈ, క్యా, ం, పె, యిన్, న...  [2017, , 18, ലെ, ബ, ജ, റ്റി, ല്, ന്യൂനപക്ഷ, മന...
1      [తమ, ప్రభుత్వం, సంతృప్తి, పరచడానికి, బదులు, ,,...  [ഇന്ത്യയുടെ, ഹജ്ജ്, ക്, വാ, ട്ട, യില, ്, സൗദി,...
2      [ఈ, రెండు, మంత్రిత్వ, శాఖ, ల, పాల, న, నియంత్ర,...  [ഇന്ത്യ, ഇന്ന്, ലോക, ത്തിന്റെ, മര, ുന്നു, നിര,...
3      [మంత్రి, మండలి, ఏ, న్, ష, ంట్, మాన్, యు, మెంట్...  [മന്ത്രിസഭ, പുരാതന, സ്മാരക, ങ്ങളും, പുരാവസ്തു,...
4      [పూర్వ, రంగం, :, రెండు, దేశాల, క, స్ట, మ్స్, అ...  [പശ്ചാത്തല, ം, ഇരു, രാജ്യങ്ങളിലെ, യും, ക, സ്റ്...
...                                                  ...                                                ...
10475  [కేంద్ర, ఆరోగ్య, ,, కుటుంబ, సంక్షేమ, శాఖ, సహాయ...  [ആരോഗ്യ, ,, കുടുംബ, ക്ഷ, േ, മ, സഹ, മന്ത്രി, ശ്...
10476  [లేని, పని, ప్రదేశాల, కోసం, సి, ., ఐ, ., ఐ, .,...  [ആരോഗ്യ, സംരക്ഷണ, ത്ത, െക്കുറിച്ചുള്ള, ഒരു, വെ...
10477  [యొక్క, ఆర్థిక, భారం, చాలా, ఎక్కువగా, ఉంది, .,...  [ജീവന, ും, പണ, വും, തൊഴിൽ, ദിന, ങ്ങളും, കണക്ക,...
10478  [ఈ, సమస్య, పై, ప్రభుత్వం, స్పందన, గురించి, ఆయన...  [, ക്ഷയ, രോഗ, ചി, ക, ിൽ, സ, ക്കുള്ള, വിഭവ, വി,...
10479  [", ఇ, , సం, జీవ, ని, టెలి, , కన్, సల్, టేషన్,...  [ഇ, , സ, ഞ്ജ, ീ, വ, നി, ടെലി, കൺ, സ, ൾ, ട്ട, േ...

[10480 rows x 2 columns]

In [ ]:
max_tel = 0
max_mallu = 0

for i in range(len(df_tokenized_data['te'])):
  if(len(df_tokenized_data['te'][i])>max_tel):
    max_tel = len(df_tokenized_data['te'][i])


for i in range(len(df_tokenized_data['ml'])):
  if(len(df_tokenized_data['ml'][i])>max_mallu):
    max_mallu = len(df_tokenized_data['ml'][i])

print("Padding Length of Telugu Dataset = ",max_tel)
print("Padding Length of Malayalam Dataset = ",max_mallu)

Padding Length of Telugu Dataset =  329
Padding Length of Malayalam Dataset =  311


In [ ]:
#pip install --upgrade torchtext
#Creating a Field
import os
from torchtext.data import Field, BucketIterator
from torch.utils.tensorboard import SummaryWriter

In [ ]:
#Padding
'''
from tensorflow.keras.preprocessing.sequence import pad_sequences
def pad(x, length):
  return pad_sequences(x, maxlen=length, padding='post')

temp_list = pad(df_tokenized_data['te'][10],max_tel)
'''

In [ ]:
#Train  and Test set
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_tokenized_data, test_size=0.2, random_state=42, shuffle=True)
train

te                                                 ml
3652  [మరిన్ని, వివరాల, కు, ., ., ., కో, వి, డ్, , 1...  [കേന്ദ്ര, കൃഷി, മന്ത്രി, സംസ്ഥാന, കൃഷി, മന്ത്ര...
5032  [వారి, సందేశం, ఏ, ఒక్క, పరిస్థితి, కి, లేదా, ఏ...  [നിരവധി, സാഹചര്യ, ങ്ങളിലൂടെ, യും, അവസ്ഥ, കളിലൂ...
9019  [మొత్తం, కేసులు, :, 49, ,, 6, 50, ;, యా, క్టివ...  [കോ, വി, ഡ്, , 19, , മായി, ബന്ധപ്പെട്ട, സാങ്കേ...
7205  [పాల్గొనే, దేశాల, అనుభవం, మరియు, వైవిధ్య, ాన్న...  [പങ്കാളിത്ത, രാജ്യങ്ങളുടെ, മുൻപ, രി, ച, യ, വും...
1313  [డాక్యుమెంట్, లు, ,, రికార్డ, ిం, గుల, సమర్పణ,...  [സവിശേഷത, കള, ്, :, 1, ., സമ, ന്, സു, ം, മറ്റു...
...                                                 ...                                                ...
5734  [ఒ, సి, ఐ, కార్డు, క, లి, గి, విదేశాల, లో, చిక...  [വിദേശ, ത്ത്, കുടു, ങ്ങി, ക്കിടക്കുന്ന, ചില, വ...
5191  [మానవ, వనరుల, అభివృద్ధి, మంత్రిత్వ, శాఖ, కో, వ...  [മാന, വ, വിഭവ, ശേഷി, വികസന, മന്ത്രാലയ, ം, കോ, ...
5390  [రాష్ట్ర, ప, తి, స, చి, వాల, యం, ఫ, క్ర, ుద్దీ...  [രാഷ്ട്രപതി, യുടെ, കാര്യ, ാലയ, ം, ഫ, ക്ര, ു, ദ...
860   [ఇది, భూమి, యొక్క, రిమోట్, సెన్, సింగ్, రంగంలో...  [ഭൂമിയുടെ, വിദൂര, സം, വേദന, ം, ,, ഉപഗ്രഹ, ഗതി,...
7270  [కో, వి, డ్, , 19, పై, ముఖ్య, మంత్ర, ులతో, చర్...  [സംസ്ഥാന, ങ്ങളിലെ, യും, കേന്ദ്ര, ഭരണ, പ്രദേശങ്...

[8384 rows x 2 columns]

In [ ]:
test

te                                                 ml
10125  [అధిక, ప్రభావ, శీల, పరి, యోజన, లు, మెరుగైన, భూ...  [മികച്ച, ഫലം, ന, ല്, കുന്ന, പദ്ധതി, കളും, മികച...
1082   [దేశంలో, వామ, పక్ష, తీవ్రవాద, ం, తగ్గుముఖం, పట...  [രാജ്യത്ത്, ഇട, ത്, തീവ്രവാദ, ത്തില, ്, കുറവ, ...
713    [పూర్వ, రంగం, :, జ, పాన్, కు, ఇనుప, ఖ, నిజ, ాన...  [പശ്ചാത്തല, ം, ജപ്പാ, ന, ിലേക്ക്, ഇന്ത്യ, യില,...
1683   [దీనికి, తోడు, ,, ఫె, లో, శి, ప్, ప, థ, కం, లో...  [കേന്ദ്ര, ാവിഷ്, , കൃത, പദ്ധതി, കളുടെ, ഗുണ, ഭ,...
1111   [ఆసియా, క్రీడ, ల, లో, భార, త, దేశానికి, ఇంత, క...  [മെ, ഡ, ല്, ജേ, താ, ക്, കളെ, അഭി, ന, ന്ദ, ിച്ച...
...                                                  ...                                                ...
9289   [కో, వి, డ్, వ్యాప్తి, నియంత్రణ, కు, సంబంధించి...  [ആരോഗ്യ, സേ, തു, മൊ, ബൈ, ല്, ആ, പ്പ്, ,, സെ, ല...
7899   [నిర, ాశ్రయ, ులకు, ఆశ్రయం, కల్పించ, డానికి, 1....  [ഭവന, രഹിത, ർക്ക്, അഭയം, നൽക, ാനായി, 1, ., 5, ...
6167   [రి, జ, , ర్, వేష, , న్, కౌ, ంట, , ర్లు, ,, కా...  [20, 20, മെയ്, 22, മുതൽ, ക്കു, തന്നെ, റെയിൽവേ,...
3895   [సివిల్, సర్వీసెస్, , 20, 20, (, ప్రి, లి, మ్స...  [സി, വില, ്, സര, ്, വീ, സസ്, , 20, 20, , (, പ്...
7699   [జిడిపి, కి, ఈ, రంగం, వాటా, (, ప, రి, శ్రమ, లు...  [പ്രതിസന്ധി, കൾ, നിലനിൽക്ക, െ, തന്നെ, വെറും, 2...

[2096 rows x 2 columns]

In [ ]:
len(train['te'][5734])

56

In [ ]:
from inltk.inltk import get_embedding_vectors
temp1 = ' '.join([str(elem) for elem in train['te'][5734]])
vectors = get_embedding_vectors(temp1, 'te')
vectors

/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute o

[array([ 0.121014, -0.039971,  0.017897, -0.089001, ...,  0.056123, -0.099884,  0.028855, -0.007437], dtype=float32),
 array([ 0.026562, -0.031423, -0.026075, -0.012581, ...,  0.117023,  0.007462,  0.08244 , -0.029031], dtype=float32),
 array([ 0.163967, -0.025337,  0.011344, -0.020088, ...,  0.115858, -0.05619 ,  0.124178, -0.05209 ], dtype=float32),
 array([-0.098227,  0.072669, -0.229882,  0.007156, ..., -0.031574,  0.02882 ,  0.03797 ,  0.009204], dtype=float32),
 array([ 0.059432, -0.032997,  0.058141, -0.156609, ...,  0.051942, -0.079955,  0.063443, -0.019937], dtype=float32),
 array([ 0.031306,  0.007392,  0.100643, -0.002218, ...,  0.127227,  0.060473,  0.019537,  0.056394], dtype=float32),
 array([ 0.109125, -0.131336, -0.081647, -0.046194, ..., -0.016462, -0.015138, -0.007976, -0.076826], dtype=float32),
 array([-0.082011, -0.037638, -0.068431, -0.014667, ..., -0.008892, -0.041015, -0.00701 , -0.158006], dtype=float32),
 array([ 0.269572,  0.282606, -0.050005, -0.100556, ...,

In [ ]:
def get_vectors(i,lang):
  temp1 = ' '.join([str(elem) for elem in df_tokenized_data[str(lang)][i]])
  vectors = get_embedding_vectors(temp1, str(lang))
  return vectors


In [ ]:
tel_vectors = {}
for j in range(len(df_tokenized_data['te'])):
  for i in range(len(df_tokenized_data['te'][j])):
    temp = get_vectors(j,'te')
    tel_vectors[str(j)] = temp
    #pass

/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute o

In [ ]:
import os
from torchtext.data import Field, BucketIterator
from torch.utils.tensorboard import SummaryWriter
telugu_field = Field()
mallu_field = Field()

In [ ]:
import torch
import torch.nn as nn
import spacy
from torchtext.data.metrics import bleu_score
import sys


def translate_sentence(model, sentence, german, english, device, max_length=50):
    # Load german tokenizer
    spacy_ger = spacy.load("de")

    # Create tokens using spacy and everything in lower case (which is what our vocab is)
    if type(sentence) == str:
        tokens = [token.text.lower() for token in spacy_ger(sentence)]
    else:
        tokens = [token.lower() for token in sentence]

    # Add <SOS> and <EOS> in beginning and end respectively
    tokens.insert(0, german.init_token)
    tokens.append(german.eos_token)

    # Go through each german token and convert to an index
    text_to_indices = [german.vocab.stoi[token] for token in tokens]

    # Convert to Tensor
    sentence_tensor = torch.LongTensor(text_to_indices).unsqueeze(1).to(device)

    outputs = [english.vocab.stoi["<sos>"]]
    for i in range(max_length):
        trg_tensor = torch.LongTensor(outputs).unsqueeze(1).to(device)

        with torch.no_grad():
            output = model(sentence_tensor, trg_tensor)

        best_guess = output.argmax(2)[-1, :].item()
        outputs.append(best_guess)

        if best_guess == english.vocab.stoi["<eos>"]:
            break

    translated_sentence = [english.vocab.itos[idx] for idx in outputs]
    # remove start token
    return translated_sentence[1:]


def bleu(data, model, german, english, device):
    targets = []
    outputs = []

    for example in data:
        src = vars(example)["src"]
        trg = vars(example)["trg"]

        prediction = translate_sentence(model, src, german, english, device)
        prediction = prediction[:-1]  # remove <eos> token

        targets.append([trg])
        outputs.append(prediction)

    return bleu_score(outputs, targets)


def save_checkpoint(state, filename="my_checkpoint.pth.tar"):
    print("=> Saving checkpoint")
    torch.save(state, filename)


def load_checkpoint(checkpoint, model, optimizer):
    print("=> Loading checkpoint")
    model.load_state_dict(checkpoint["state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer"])